### ISSUE TITLE
Meta issue for JavaScript startup issues

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/OpenSlides#2854]
*  [x] #1460 Send all needed data after first connection
* [x] #1820 first load whoami and then load all data 
* [x] #1851 Get rid of user.findAll() 
* [x] #2295 Load all at the beginning 
* [x] #2403 Startup of webclient 
* [x] #2588 Operator is not load at reload 
* [x] #2775 Proposal for temporary solution for startup process 
* [ ] (#2417 Projector container should not listen on the same channel as real projector. )
* [ ] (#2568 OS 2.1: blocker: motions are deleted on saving motion block settings )

**Comment by ostcar** [comment]
Are you sure, that Get rid of user.findAll() is fixed? I can find a lot of this lines in the master. 

It is especially not fixed with #2856

**Comment by emanuelschuetze** [comment]
Done with #2863
