### ISSUE TITLE
OS3 Client CSS metaissue

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#3951]
Feel free to add things to do.

- [x] When a user logges in the sidebar has a too large margin (255px instead of 240px). Doing any resize event or interaction updates the DOM and the sidebar updates the wrong margin. See image below.
![not-updating-dom](https://user-images.githubusercontent.com/8439581/47602127-48aa0500-d9da-11e8-9cce-3e58a2f13fcf.jpg)

**Comment by tsiegleauq** [comment]
@FinnStutzenstein cannot reproduce in current firefox nor chromium

 - logged out
 - set browser width to 960px (lowest "desktop" resolution)
 - cleared both caches
 - logged in
 - looks fine

However, what I did notice is that:

- [ ]  the side panel grows with the username. Should probably have a fixed width of `240px`.

**Comment by jsaalfeld** [comment]
I noticed:
 - [ ] Login-Page: When Page-height is too small the Login-Button will be hidden by the footer. (If the page-heigth is reduced even more, the login button, and everything else, will appear below the footer.

**Comment by tsiegleauq** [comment]
Found out, the issue with the side panel only occurs (/seems only to occur) when you have your dev-tools open and put on the bottom.

**Comment by jsaalfeld** [comment]
- [ ] The text in the motion comment fields looks off. it should be left on top and next to it there should be the edit button (#3929)

**Comment by jsaalfeld** [comment]
* [ ] Color for  `.file-drop-style` or theme for the `ngx-file-drop` should be overhauled and fit to the overall oing of CSS-Standard in OS.

**Comment by FinnStutzenstein** [comment]
We need pointer (for the cursor) on mat-chips, if a dropdown opens (see motion detail view)

**Comment by FinnStutzenstein** [comment]
Also: in the motion detail mat-chipy should not ripple, if they are not clickable. Also some dividers need to be hidden, if no entries are above or below them.
The text `---` (set null) needs to be changed to `set null`, which should be displayed grey.

**Comment by GabrielInTheWorld** [comment]
![list of speakers](https://user-images.githubusercontent.com/10206688/52340826-1b291a80-2a11-11e9-8e4c-f01854cee4d7.png)

At the agenda the heading (h1) should have the same margin as the other content below.
In addition there should be at least some margin to the toolbar.

**Comment by FinnStutzenstein** [comment]
![zindex](https://user-images.githubusercontent.com/8439581/53864564-15f9c400-3fed-11e9-8b44-8aec5747a331.jpg)

- [ ] At least the topic edit (may also create) form lays ontop of the headbar.

**Comment by MaximilianKrambach** [comment]
>
> * [ ]  At least the topic edit (may also create) form lays ontop of the headbar.

Seems like the same issue as #4442 (everything with `on-transistion-fade` got a ridiculous z-index)

**Comment by tsiegleauq** [comment]
Cannot reproduce.
- browser
- version
- steps to reproduce?

![image](https://user-images.githubusercontent.com/10233032/53868980-8574b100-3ff7-11e9-8bf7-8da98163ecce.png)

**Comment by MaximilianKrambach** [comment]
In the topic edit form, this can reproduced by limiting the browser's height to about half a screen.
In a topic detail view, the topic's content just needs to be long enough.
Both observed in chromium.

**Comment by tsiegleauq** [comment]
Can confirm this happens when you are actively resizing the browser windows in that view.
If you are not resizing your viewport it will not happen.

**Comment by FinnStutzenstein** [comment]
![los](https://user-images.githubusercontent.com/8439581/53892209-254c3200-402c-11e9-938e-0078753ccc2e.jpg)

The list of speakers (last speaker section) has some flaws:
@ctschup Can you think of a better way to place these buttons. It's not nice how they are flapping around.. Also some other button design
@MaximilianKrambach You did the unix<->human time convertion. The `m` is redundant here.. Please fix this.

**Comment by FinnStutzenstein** [comment]
![padding](https://user-images.githubusercontent.com/8439581/53892347-68a6a080-402c-11e9-98bc-badfe3c5acaa.jpg)

In the projector detail view. A bit of left and right padding would be nice.

**Comment by MaximilianKrambach** [comment]
> @MaximilianKrambach You did the unix<->human time convertion. The m is redundant here.. Please fix this.

See #4469

**Comment by FinnStutzenstein** [comment]
![theme-login](https://user-images.githubusercontent.com/8439581/54016482-6c007000-4183-11e9-9c80-7e26e860ec4a.jpg)

@GabrielInTheWorld With #4473 the theme is also applied to the login page. At least with the red theme, the inputs are not visible. Please also check all other themes.

**Comment by tsiegleauq** [comment]
- [ ] use the parent-selector over ::ng-deep (`&.class`)
- [ ] [view encapsulation](https://blog.thoughtram.io/angular/2015/06/29/shadow-dom-strategies-in-angular2.html) can be used, if deeper components cannot be styles. It's not necessary to write everything in the globaly `style.scss`

**Comment by FinnStutzenstein** [comment]
@tsiegleauq @GabrielInTheWorld The webpage has a double-scrollbar when the offline message is shown
![double-scroll](https://user-images.githubusercontent.com/8439581/64114471-587a3e80-cd8d-11e9-8af9-619e9930de35.jpg)

**Comment by tsiegleauq** [comment]
nothing left to do so far.
If anything else occurs create a new issue.
