### ISSUE TITLE
[meta] Change the model format

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/OpenSlides#6207]
@normanjaeckel I collect places that needs to be adjusted

- [x] Main files (https://github.com/OpenSlides/OpenSlides/pull/6203)
- [x] Datastore (https://github.com/OpenSlides/openslides-datastore-service/pull/145)
- [x] Backend (https://github.com/OpenSlides/openslides-backend/pull/902)
- [x] Autoupdate service: @ostcar @r-peschke do you use the `initial-data.json` or `example-data.json`?
- [x] https://github.com/OpenSlides/OpenSlides/blob/stable/3.4.x/server/openslides/core/export.py

**Comment by r-peschke** [comment]
As far as I know the autoupdate-service use the example-data.json as base for the manual operated tests

**Comment by FinnStutzenstein** [comment]
So there is one point left. If this is done, everything can be merged I think.
