### ISSUE TITLE
Integration tests - leftovers and todos

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/OpenSlides#6227]
Cypress Tests are usually working fine by now. There are some things that still need to be done anyways:

- [ ] apparently, even when a tests fails, github actions returns that the integration tests were running without errors. That might a GHActions bug, a docker bug or I missed something during configuration
- [ ] we need to flush the DataStore between the tests, so the tests can run in a clean environment
- [ ] we need to create users in the DataStore between tests, so we can also test permissions
- [ ] MediaManageService needs to be tested
