### ISSUE TITLE
OpenTelemetry

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/OpenSlides#6337]
This is a meta-issue to track the progress of all services to implement [OpenTelemetry](https://opentelemetry.io/)

* [ ] [openslides-icc-service](https://github.com/OpenSlides/openslides-icc-service/issues/40)
* [ ] [openslides-autoupdate-service](https://github.com/OpenSlides/openslides-autoupdate-service/issues/401)
* [x] [openslides-auth-service](https://github.com/OpenSlides/openslides-auth-service/issues/120)
* [ ] [openslides-icc-service](https://github.com/OpenSlides/openslides-icc-service/issues/40)
* [x] [openslides-backend](https://github.com/OpenSlides/openslides-backend/issues/1153)
* [ ] [openslides-media-service](https://github.com/OpenSlides/openslides-media-service/issues/45)
* [ ] [openslides-manage-service](https://github.com/OpenSlides/openslides-manage-service/issues/153)
* [x] [openslides-datastore-service](https://github.com/OpenSlides/openslides-datastore-service/issues/177)

There are also some changes needed in the main repo. Jaeger and the otel-collector have to be configured for the dev-environment. See https://github.com/OpenSlides/OpenSlides/pull/6322/files
